### ISSUE TITLE
data structure of baseline.yml

### ISSUE THREAD

**Issue by aaronlippold** [dev-sec/dev-sec.github.io#29]
@mtollick and @aaronlippold were looking at streamlining some of the upkeep on the site

In reviewing the https://github.com/dev-sec/dev-sec.github.io/blob/src/data/baselines.yml file it seems that we sould really have a structure like: 

This would allow us to create a more standard approach on auto processing this and looping for rebuilding source data as we need to.

```yaml
baselines:
  - name: linux
     id: linux-baseline
     type: os|app|ops|comp|net|plat
     links:
       - name: InSpec Profile
         url: https://github.com/dev-sec/linux-baseline
         icon: icon-github-circled
       - name: Ansible Remediation Role
         url: https://github.com/dev-sec/ansible-os-hardening
         icon: icon-github-circled
       - name: Chef Remediation Cookbook
         url: https://github.com/dev-sec/chef-os-hardening
         icon: icon-github-circled
       - name: Puppet Remediation Module
         url: https://github.com/hardening-io/puppet-os-hardening
         icon: icon-github-circled
  - name: ssh
     ...
```
